## Numpy operations

In [2]:
import numpy as np       # constructing an array list
l=np.arange(20)**3
l

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859], dtype=int32)

In [3]:
for j in l :                # iterating through the array list
    print(j**1/5)

0.0
0.2
1.6
5.4
12.8
25.0
43.2
68.6
102.4
145.8
200.0
266.2
345.6
439.4
548.8
675.0
819.2
982.6
1166.4
1371.8


In [5]:
colors=np.array([['red','green'],['orange','white'],['brown','violet']])   # creating array of same order list
colors[0]

array(['red', 'green'], dtype='<U6')

In [6]:
colors[1]

array(['orange', 'white'], dtype='<U6')

In [7]:
for each in colors:           # iterating  through the list with index named as 'i'
    print('i=',each)

i= ['red' 'green']
i= ['orange' 'white']
i= ['brown' 'violet']


In [8]:
colors

array([['red', 'green'],
       ['orange', 'white'],
       ['brown', 'violet']], dtype='<U6')

In [9]:
for eachh in colors.flatten():          # Row major flattening
    print(eachh)

red
green
orange
white
brown
violet


In [4]:
import numpy as np
colors=np.array([['red','green'],['orange','white'],['brown','violet']])     # column major flattening
for eachh in colors.flatten(order='F'):
    print(eachh)

red
orange
brown
green
white
violet


In [3]:
import numpy as np
arr=np.array([['vivek','pranjal'],['ajay','vkkkkkk'],[30,40]])                # column major flattening
for k in arr.flatten():
    print(k)

vivek
pranjal
ajay
vkkkkkk
30
40


In [11]:
k=np.arange(15).reshape(3,5)                   # creating array with reshape function to change it in matrix
k

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
for m in np.nditer(k):                   # iterating through the matrix-----Row major
    print(m)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [14]:
for j in np.nditer(k,order='F'):                        # iterating through the matrix-----Column major
    print(j)

0
5
10
1
6
11
2
7
12
3
8
13
4
9
14


In [11]:
!pip install iteration_utilities

In [44]:
from iteration_utilities import deepflatten
import numpy as np
colors=np.array([['red','green','white'],['orange'],['brown','sky','tree']])   # deepflatttenig using external package
for h in deepflatten(colors):
    print(h)

r
e
d
g
r
e
e
n
w
h
i
t
e
o
r
a
n
g
e
b
r
o
w
n
s
k
y
t
r
e
e



## Set operations



In [12]:
set1={"a","b","c","c","d","b"}
set1

{'a', 'b', 'c', 'd'}

In [13]:
set2={1,2,3,4,5,"a","c"}
set2

{1, 2, 3, 4, 5, 'a', 'c'}

In [14]:
set1 & set2                 # intersection of sets

{'a', 'c'}

In [15]:
set1.union(set2)             # union of sets

{1, 2, 3, 4, 5, 'a', 'b', 'c', 'd'}

In [16]:
set1.issubset(set2)           # checking for subset

False

In [17]:
list1=["a","b","c","d"]          # alternate way of counting indices
for i,x in enumerate(list1):
    print(i,x)

0 a
1 b
2 c
3 d


In [18]:
for i,x in range (enumerate(10)):
    print(i,x)

TypeError: 'int' object is not iterable

In [19]:
for i,x in enumerate(range(10)):        #counting in particular range
    print(i,x)

0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9


In [23]:
for i,x in enumerate(range(100,110),1):     #defining own index
    print(i,x)

1 100
2 101
3 102
4 103
5 104
6 105
7 106
8 107
9 108
10 109


In [24]:
list2=["aman","aman","aman","aman","aman","raman","sarman"]
l=[]
i=0
while(list2[i]=="aman"):
    l.append(list2[i])
    i+=1
print(l,i)
for v,x in enumerate(l):      # creating a list and counting the element through enumerate method

    print(v,x)

['aman', 'aman', 'aman', 'aman', 'aman'] 5
0 aman
1 aman
2 aman
3 aman
4 aman


In [25]:
def fun1(*names):               # addding as many name we want using * in a function
    for name in names:
        print(name)
        
fun1("q","w","r","s","y")        

q
w
r
s
y


## Introduction to pandas


In [2]:
import pandas as pd
import numpy as np

In [3]:
a=pd.Series()      # creating a series in panda
print(a)

Series([], dtype: float64)


In [4]:
first=np.array(['i','we','they','our','her'])     # formatting array into series
second=pd.Series(first)
second

0       i
1      we
2    they
3     our
4     her
dtype: object

In [5]:
second=pd.Series(first,index=[10,20,30,40,50])     # giving own index to the series
second

10       i
20      we
30    they
40     our
50     her
dtype: object

In [7]:
third={'a':0.00,'b':1.10,'c':2.20,'d':3.30}          # creating series for dictionaries
fourth=pd.Series(third)
print(fourth)

a    0.0
b    1.1
c    2.2
d    3.3
dtype: float64


In [14]:
fifth=pd.Series(fourth,index=['d','b','e','f','c','a'])   # printing own indices
fifth

d    3.3
b    1.1
e    NaN
f    NaN
c    2.2
a    0.0
dtype: float64

In [15]:
fifth.values                 # finding the values by .value method

array([3.3, 1.1, nan, nan, 2.2, 0. ])

In [16]:
fifth.index                 # finding the index by .index method

Index(['d', 'b', 'e', 'f', 'c', 'a'], dtype='object')

In [18]:
sixth=pd.Series([4,9,16,25,36],index=['d','e','f','g','h'])   # alternative ways to creat series
print(sixth)

d     4
e     9
f    16
g    25
h    36
dtype: int64


In [20]:
sixth['f']                   # retrieving the element through index value

16

In [22]:
sixth[['f','e','h']]          # retrieving the element through multiple index value

f    16
e     9
h    36
dtype: int64

In [33]:
sixth[sixth>=16]            # retrieving the element whose value is greater than or equal to 16

f    16
g    25
h    36
Name: Square of number*2, dtype: int64

In [37]:
seventh=sixth*2                          # computing square of the series formed
seventh.name='Square of number*2' 
print(seventh)

d     8
e    18
f    32
g    50
h    72
Name: Square of number*2, dtype: int64


In [42]:
seventh.index=['2 sqr *2 =','3 sqr *2 =','4 sqr *2 =','5 sqr *2 =','6 sqr *2 =']     #Altering the index values 
print(seventh)

2 sqr *2 =     8
3 sqr *2 =    18
4 sqr *2 =    32
5 sqr *2 =    50
6 sqr *2 =    72
Name: Square of number*2, dtype: int64
