In [1]:
!pip install numpy

In [2]:
!pip install numpy --upgrade

  Found existing installation: numpy 1.15.4
    Uninstalling numpy-1.15.4:
      Successfully uninstalled numpy-1.15.4


In [1]:
import numpy as np                               # importing numpy for n-dimensional array creation          

num=np.array([100,200,300,400,500])              #creating an array and printing

num

array([100, 200, 300, 400, 500])

In [2]:
type(num)                             # using type fnctn for finding type of num

numpy.ndarray

In [5]:
num1=[10,20,30,40,50]

num3=np.array(num1)                 #creating an array and printing

print(num3)

[10 20 30 40 50]


In [16]:
num4=num+num3                        # Adding the two previous created array

print(num4)


[110 220 330 440 550]


In [9]:
zeros_array=np.zeros([4,4])           # creating 4*4 matrix of zero using built in functions
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
range1=np.arange(10)                     # creating an array in range 0 to 10 using arange
print(range1)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
range2=np.arange(10,20)                   # creating an array in range 10 to 20 using arange
print(range2)

[10 11 12 13 14 15 16 17 18 19]


In [31]:
range2=np.arange(1,40,2)                 # creating an array in range 1 to 40 with step of 2 using arange
print(range2)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


In [32]:
range2.shape=5,4                   # Now conerting it to matrix form using shape funtion
print(range2)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]
 [33 35 37 39]]


In [33]:
range2[3]                         # printing 4rt row from matrix ie.--3 means 3+1=4rth row

array([25, 27, 29, 31])

In [34]:
range2[4]                        # printing 5th row

array([33, 35, 37, 39])

In [35]:
range3=range2*5                   # multiplying the matrix by 5 and printing the result
print(range3)

[[  5  15  25  35]
 [ 45  55  65  75]
 [ 85  95 105 115]
 [125 135 145 155]
 [165 175 185 195]]


In [36]:
range3[2,2]=200                   # changing the value in 3rd row of 3rd element
print(range3)

[[  5  15  25  35]
 [ 45  55  65  75]
 [ 85  95 200 115]
 [125 135 145 155]
 [165 175 185 195]]


In [38]:
range3[1,2:4]=50,80               # changing the value in 2nd row of 3rd and 4rth element
print(range3)

[[  5  15  25  35]
 [ 45  55  50  80]
 [ 85  95 200 115]
 [125 135 145 155]
 [165 175 185 195]]


In [39]:
range3[3]=0                       # changing all values to 0 in row 4.
print(range3)

[[  5  15  25  35]
 [ 45  55  50  80]
 [ 85  95 200 115]
 [  0   0   0   0]
 [165 175 185 195]]


In [40]:
print(range3[3,0:4])            # printing the values in row4 from 1st element to 4rth element

[0 0 0 0]


In [42]:
range3.shape                   # finding order of the matrix

(5, 4)

In [43]:
range3.size                    # size of matrix means no of element in it

20

In [44]:
range3.ndim                    # finding dimension of the matrix

2

In [46]:
float1=np.arange(2.2,24.4,2)            # creating array of float values
print(float1)

[ 2.2  4.2  6.2  8.2 10.2 12.2 14.2 16.2 18.2 20.2 22.2 24.2]


In [47]:
float1.shape=3,4                      # matrix formation
print(float1)

[[ 2.2  4.2  6.2  8.2]
 [10.2 12.2 14.2 16.2]
 [18.2 20.2 22.2 24.2]]


In [48]:
float2=float1*0.5                      # multiplication by 0.5
print(float2)

[[ 1.1  2.1  3.1  4.1]
 [ 5.1  6.1  7.1  8.1]
 [ 9.1 10.1 11.1 12.1]]


In [53]:
float3=np.arange(15,27)
print(float3)

[15 16 17 18 19 20 21 22 23 24 25 26]


In [54]:
float4=float3*float2          # tryied to multiply matrices of different order

ValueError: operands could not be broadcast together with shapes (12,) (3,4) 

In [57]:
float3.shape=3,4                 # So converting to same order and then multiplying
float4=float3*float2
print(float4)

[[ 16.5  33.6  52.7  73.8]
 [ 96.9 122.  149.1 178.2]
 [209.3 242.4 277.5 314.6]]


In [64]:
import numpy as np                  # calculating the dot product of the two matrix
float5=np.dot(float2,float3)
print(float5)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [59]:
float2.ndim

2

In [60]:
float3.ndim

2