In [4]:
first_name='vivek'
last_name='tiwari'
print(first_name.title() + ' ' + last_name.title())

Vivek Tiwari


In [5]:
first_name.lower()

'vivek'

In [6]:
first_name.upper()

'VIVEK'

In [15]:
bikes=['yamaha','suzuki','hero','tvs','bullet']

print(bikes[0],'\n')

print(bikes[2],'\n')

print(bikes[1],'\n')

print(bikes[-2],'\n')



yamaha 

hero 

suzuki 

tvs 



In [16]:
for name in bikes:
    print(name,'\n')

yamaha 

suzuki 

hero 

tvs 

bullet 



In [19]:
count=1
for name in bikes:
    print(name,count,'\n')
    count+=1

yamaha 1 

suzuki 2 

hero 3 

tvs 4 

bullet 5 



In [20]:
bikes.append('bajaj')
bikes.append('ktm')
bikes.append('honda')


In [22]:
print(bikes)

['yamaha', 'suzuki', 'hero', 'tvs', 'bullet', 'bajaj', 'ktm', 'honda']


In [25]:
empty=[]
for x in range(1,20):
    empty.append(x**2)
    print(x)
print(empty)    

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361]


In [27]:
squares  = [x**2 for x in range(1,11)]
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [7]:
names=['vivek','jenny','atul','moumita']
slice=names[:3]
print(slice)

['vivek', 'jenny', 'atul']


In [15]:
import numpy as np
salaries=np.genfromtxt('Salary_Data.csv',delimiter=',')
salaries

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [16]:
salaries.shape

(30,)

In [17]:
mean=np.mean(salaries)
median=np.median(salaries)
sd=np.std(salaries)
variance=np.var(salaries)

print('mean = %i' %mean)

print('median = %i' %median)

print('sd = %i' %sd)

print('variance = %i' %variance)

mean = 76003
median = 65237
sd = 26953
variance = 726499261


In [18]:
a = np.arange(11)**2

In [19]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [20]:
a[1]

1

In [21]:
a[5]

25

In [22]:
a[-5]

36

In [23]:
a[-3]

64

In [24]:
a[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0], dtype=int32)

In [25]:
a[0:3]

array([0, 1, 4], dtype=int32)

In [27]:
customers=np.array([['ram','shyam','mohan','sohan','mahesh'],[75,89,80,77,80],[60,52,66,70,65]])

In [28]:
customers[0]

array(['ram', 'shyam', 'mohan', 'sohan', 'mahesh'], dtype='<U6')

In [29]:
customers[2]

array(['60', '52', '66', '70', '65'], dtype='<U6')

In [39]:
customers[0,3]

('sohan', '77')

In [41]:
customers[0,3],[1,3]

('sohan', [1, 3])

In [42]:
customers([0,3],[1,3])


TypeError: 'numpy.ndarray' object is not callable

In [43]:
customers[0,3],customers[1,3]

('sohan', '77')

In [59]:
import csv
with open('winequality-red.csv', 'r') as file:
    #wines = np.genfromtxt('winequality-red.csv',delimiter=';')
    wines = list(csv.reader(file, delimiter=';'))
    
    print(wines[:3])
    
    
    
    
    

[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality'], ['7.4', '0.7', '0', '1.9', '0.076', '11', '34', '0.9978', '3.51', '0.56', '9.4', '5'], ['7.8', '0.88', '0', '2.6', '0.098', '25', '67', '0.9968', '3.2', '0.68', '9.8', '5']]


In [68]:
with open('winequality-red.csv', 'r') as file:
    
    winess = list(csv.reader(file, delimiter=';'))
    
    for i in wines[:3]:
        print(i)

['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality']
['7.4', '0.7', '0', '1.9', '0.076', '11', '34', '0.9978', '3.51', '0.56', '9.4', '5']
['7.8', '0.88', '0', '2.6', '0.098', '25', '67', '0.9968', '3.2', '0.68', '9.8', '5']


In [66]:
qualities=[float(items[-1]) for items in wines[1:]]
sum(qualities)/len(qualities)

5.6360225140712945

In [71]:
import numpy as np
wines=np.array(wines[1:], dtype=float)

In [72]:
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [73]:
wines.shape

(1599, 12)

In [74]:
wines[0:3,3]

array([1.9, 2.6, 2.3])