In [3]:
print("Welcome to FRUITS BAZAR")
money=int(input("Enter how much money you have?"))
fruits={'apple':10,'banana':12,'guava':30,'mango':40}
for items in fruits:
    
    print('Each ' + items + ' costs Rs: ' + str(fruits[items]))
    
   # temp=input("Which fruit do you want to buy: ")
    
   # for temp in items:
        
    count=int(input("How many "+ items + " do you want"))
        
    print('you will buy ' +str(count)+ '' + items + 's')
        
    totalprice=count*fruits[items]
        
    print('the total price is '+ str(totalprice) +' Rs')
        
    if money >= totalprice:
        print('You have bought ' + str(count) + ' ' + items + 's')
            
        money-=totalprice
            
        if money==0:
            print('your wallet is empty now')
                
        break
            
    else:
                
        print('You do not have enough money')
        print('You cannot buy that maqny ' + items + 's')

print('You have '+ str(money)+ ' dollars left')            

Welcome to FRUITS BAZAR
Enter how much money you have?80
Each apple costs Rs: 10
How many apple do you want5
you will buy 5apples
the total price is 50 Rs
You have bought 5 apples
You have 30 dollars left


In [10]:
def validate(pname):
    if pname>=0 or pname<=7:
        return True
    
    else:
        return False




def fun1(pname,team='delhi daredevils'):
    
    pnames=['v.shewag','dhoni','i.pathan','jack kallis','ab.deviliers','shane watson','virat kohli','hardik pandya']
    print(f"{pnames[pname].title()} is associated with {team.title()}")
    
print('Welcome to the IPL Auction')

teamname=input('Enter the team name: ')

print('Pick a player: (0: v.shewag,1: dhoni,2: i.pathan,3: jack kallis,4: ab.deviliers,5: shane watson,6: virat kohli,7: hardik pandya)')

playername=int(input('Enter the corresponding number of player you want'))



if validate(playername):
    
    fun1(playername,teamname)

else:
    print('Enter valid selection value')


Welcome to the IPL Auction
Enter the team name: rcb
Pick a player: (0: v.shewag,1: dhoni,2: i.pathan,3: jack kallis,4: ab.deviliers,5: shane watson,6: virat kohli,7: hardik pandya)
Enter the corresponding number of player you want9


IndexError: list index out of range

In [4]:
import numpy as np

arr1=np.array([12,14,5,8])

arr2=np.array([45,9,25,18])

print(f"\n{arr1+arr2}")
print(f"\n{arr1-arr2}")
print(f"\n{arr1*arr2}")
print(f"\n{arr1/arr2}")
print(f"\n{arr1%arr2}")


[57 23 30 26]

[-33   5 -20 -10]

[540 126 125 144]

[0.26666667 1.55555556 0.2        0.44444444]

[12  5  5  8]


In [11]:
arr=np.array([[4,5,6],[1,2,3]])
arr3=np.array([[7,8,9],[3,5,7]])

print('Array1:\n',arr)
print('Array2:\n',arr3)

Array1:
 [[4 5 6]
 [1 2 3]]
Array2:
 [[7 8 9]
 [3 5 7]]


In [12]:
arr*arr3

array([[28, 40, 54],
       [ 3, 10, 21]])

In [13]:
arr.dot(arr3)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [15]:
arr.ndim

2

In [16]:
arr3.ndim

2

In [17]:
arr4=np.array([[4,5,6],[1,2,3],[1,2,3]])
arr5=np.array([[7,8,9],[3,5,7],[1,2,3]])
arr4.dot(arr5)

array([[49, 69, 89],
       [16, 24, 32],
       [16, 24, 32]])

In [40]:
arr4@arr5

array([[49, 69, 89],
       [16, 24, 32],
       [16, 24, 32]])

In [41]:
(arr4@arr4)<100

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [24]:
t1=np.array([14465464564684354,1245435465454353,25896325874562,14569875624885])

print('Sum: ',t1.sum())

print('maximum: ',t1.max())

print('minimum: ', t1.min())

Sum:  15751366231638154
maximum:  14465464564684354
minimum:  14569875624885


In [28]:
t2=np.arange(20,50).reshape(5,6)
t2

array([[20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [29]:
t2.sum(axis=0)

array([160, 165, 170, 175, 180, 185])

In [30]:
t2.sum(axis=1)

array([135, 171, 207, 243, 279])

In [39]:
print('the mean value of the row is: ',t2.mean(axis=0,dtype=np.int16))

the mean value of the row is:  [32 33 34 35 36 37]


In [37]:
print('the mean value of the row is: ',t2.mean(axis=1))

the mean value of the row is:  [22.5 28.5 34.5 40.5 46.5]


In [45]:
t3=t2.cumsum(axis=1)
t3


array([[ 20,  41,  63,  86, 110, 135],
       [ 26,  53,  81, 110, 140, 171],
       [ 32,  65,  99, 134, 170, 207],
       [ 38,  77, 117, 158, 200, 243],
       [ 44,  89, 135, 182, 230, 279]], dtype=int32)

In [46]:
t3.T

array([[ 20,  26,  32,  38,  44],
       [ 41,  53,  65,  77,  89],
       [ 63,  81,  99, 117, 135],
       [ 86, 110, 134, 158, 182],
       [110, 140, 170, 200, 230],
       [135, 171, 207, 243, 279]], dtype=int32)

In [59]:
for rows in t3:
    print(rows)

[ 20  41  63  86 110 135]
[ 26  53  81 110 140 171]
[ 32  65  99 134 170 207]
[ 38  77 117 158 200 243]
[ 44  89 135 182 230 279]


In [48]:
for elements in t3.flat:                 # printing each elemnt of the array matrix
    print(elements)

20
41
63
86
110
135
26
53
81
110
140
171
32
65
99
134
170
207
38
77
117
158
200
243
44
89
135
182
230
279


In [57]:
c=np.arange(50)              #Automatic reshaping
d=c.reshape((5,-1,2))
d.shape


(5, 5, 2)

In [58]:
d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])